apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shop
resources:
  - namespace.yaml
  - configmap.yaml
  - storefront.yaml
  - admin.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
images:
  - name: shop-storefront
    newTag: local
  - name: shop-admin
    newTag: local
